#!/bin/sh
# mkdeepin - Deepin 的服务器 ISO 构建工具
# 王明栋（21wmd）<wangmd21@gmail.com>

source ./etc/init.sh
source ./etc/deepin.conf
source ./tools/iso/mkiso
source ./tools/rpm/mkrpm
source ./tools/src/mksrc

case $1 in
    isoinit)
        init
        isoinit
        ;;
    rpminit)
        init
        rpminit
        ;;
    cpiso)
        cpiso
        ;;
    mkiso)
        mkiso
        ;;
esac
