#!/bin/sh

for i in {1..2172}

do

    line=$i'p'
    name=$(sed -n "$line" ~/make/rpm/list) 
    mock -r deepin-15-x86_64 /data/SPackages/$name --resultdir=/data/tmp/packages
    files='ls /data/tmp/packages | grep rpm'
    if [ -z "$files" ]; then
        echo $name >> ~/make/rpm/fail
        mkdir ~/make/rpm/message/$name
        cp /data/tmp/packages/*.log ~/make/rpm/message/$name/
    else
        echo $name >> ~/make/rpm/successful
        mv /data/tmp/packages/*.rpm /data/Packages/
    fi
    echo $i >> ~/make/rpm/history-num
    echo $name >> ~/make/rpm/history-rpm
    rm /data/tmp/packages/*

done
